MyVideoGrapher/MyVideoGrapher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('init.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MyVideoGrapher/init/urls.py
from django.contrib import admin
from django.urls import path
from init import views
from django.contrib.auth import views as vew


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name = 'home'),
    path('setupStudio/',views.setupStudio,name = 'setupStudio'),
    path('login/',vew.LoginView.as_view(template_name = 'init/studiologin.html'),name = "login"),
    path('logout/',vew.LogoutView.as_view(template_name = 'init/studiologout.html'), name = 'logout'),
    path('studioProfileInfo',views.studioProfileUpdate, name = 'studioProfileInfo'),
    path('addCam/',views.addCam,name = 'addCam'),
    path('editCamdetails/<int:id>/',views.editCamdetails,name = 'editCamdetails' ),
    path('viewProfile/<int:id>/',views.viewProfile,name = 'viewProfile'),
    path('userRegister/',views.userReg,name = 'userRegister'),
    path('passwordchange/',views.changepwd,name = 'passwordchange'),
    path('camView/<int:id>/',views.camview, name = 'camView'),
    path('deleteCam/<int:id>/',views.deleteCam, name = 'deleteCam'),
    path('orderform/<int:id>/',views.orderform,name = 'orderform'),
    path('myorders/',views.myorders,name = 'myorders'),
    path('viewCustOrder/<int:id>/',views.viewCustOrder,name = 'viewCustOrder'),
    path('mybookings/',views.mybookings,name = 'mybookings'),
]

MyVideoGrapher/init/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    t = [(1,'VGrapher'),(2,'User')]
    role = models.IntegerField(choices=t,default=1)
    studio_name = models.CharField(max_length=300, default='')
    vaddress = models.TextField(default='')
    experience = models.IntegerField(default=0)
    Description = models.TextField(default='')
    profileImag = models.ImageField(upload_to = 'ProfilePics/',default = 'ProfilePics/07.jpg')
    hadFilled = models.BooleanField(default=False)
    

class CamModels(models.Model):
    vgId = models.ForeignKey(User,on_delete=models.CASCADE)
    camName = models.CharField(max_length=100)
    prizePerHour = models.CharField(max_length=50)
    description = models.TextField(default='')
    camPic = models.ImageField(upload_to='CamaraPics/',default = 'CamaraPics/04.jpg')
    bookedDates = models.CharField(max_length=500,default="")

class OrderModel(models.Model):
    uid = models.ForeignKey(User,on_delete=models.CASCADE)
    cid = models.IntegerField()
    nameOfEvent = models.CharField(max_length=100)
    fromDate = models.CharField(max_length=50)
    toDate = models.CharField(max_length=50)
    ceremonyTime = models.CharField(max_length=50)
    addressOfCeremony = models.TextField()
    t = [(1,'None'),(2,'Accept'),(3,'reject')]
    isAccepted = models.IntegerField(choices=t,default=1)
    email = models.EmailField()

MyVideoGrapher/init/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from init.forms import CamForm, VideoGrapherRegisterForm, VideoGrapherProfile,UserRegistForm,CustomerProfile,PasswordChange,OrderForm, viewCustOrderForm
from django.contrib.auth.decorators import login_required
from init.models import OrderModel, User,CamModels
from django.contrib.auth import authenticate, login
from MyVideoGrapher import settings
from django.core.mail import send_mail
from django.contrib import messages

# Create your views here.
def home(request):
    videog = User.objects.filter(hadFilled = 1)
    c = videog.count()
    cam = CamModels.objects.filter(vgId = request.user.id)
    try:
        x = request.user.id
        r=False
        if x is not None:
           ch = User.objects.get(id = x)
           r = ch.hadFilled
    except:
        pass
    context = {
        'videog':videog,
        'count':c,
        'hadFilled':r,
        'cam':cam,
    }
    return render(request,'init/home.html',context)

def setupStudio(request):
    f = VideoGrapherRegisterForm()    
    if request.method == 'POST':
        f = VideoGrapherRegisterForm(request.POST)
        if f.is_valid():
            u = f.save(commit = False)
            u.role = 1
            u.save()
            messages.success(request,"Studio Created Successfully")
            new_user = authenticate(username=f.cleaned_data['username'],
                                    password=f.cleaned_data['password1'],
                                    )
            login(request, new_user)
            return redirect('/')
        else:
            messages.error(request,f.errors)
    return render(request,'init/setupStudio.html',{'form':f})

@login_required
def studioProfileUpdate(request):
    us = User.objects.get(id = request.user.id)
    if request.user.role == 1:
        f = VideoGrapherProfile(instance=us)
        if request.method == 'POST':
            f = VideoGrapherProfile(request.POST,request.FILES,instance=us)
            if f.is_valid():
                u = f.save(commit = False)
                u.hadFilled = True
                u.save()
                messages.success(request,"Profile Updated Successfully")
                return redirect('home')
    else:
        f = CustomerProfile(instance=us)
        if request.method == 'POST':
            f = CustomerProfile(request.POST,request.FILES,instance=us)
            if f.is_valid():
                u = f.save(commit = False)
                u.hadFilled = True
                u.save()
                messages.success(request,"Profile Updated Successfully")
                return redirect('home')
        messages.error(request,"Something went Wrong...")
    return render(request,'init/studioProfileInfo.html',{"form":f})
    


@login_required
def addCam(request):
    f = CamForm()
    if request.method == 'POST':
        f = CamForm(request.POST,request.FILES)
        if f.is_valid():
            u = f.save(commit = False)
            u.vgId_id = request.user.id
            u.save()
            messages.success(request,"Camera Added Successfully")
            return redirect('home')
    else:
        messages.error(request,"Something Went Wrong...")
    return render(request,'init/addCam.html',{'form':f})
    
@login_required
def editCamdetails(request,id):
    t = CamModels.objects.get(id = id)
    f = CamForm(instance=t)
    if request.method == 'POST':
        f = CamForm(request.POST,request.FILES,instance=t)
        if f.is_valid():
            f.save()
            messages.success(request,"Updated Successfully")
            return redirect('home')
    return render(request,'init/camaraDetails.html',{'form':f})

def viewProfile(request,id):
    data = User.objects.get(id=id)
    cam = CamModels.objects.filter(vgId = id)
    return render(request,'init/viewProfile.html',{'data':data,'cam':cam})

def userReg(request):
    f = UserRegistForm()    
    if request.method == 'POST':
        f = UserRegistForm(request.POST)
        if f.is_valid():
            u = f.save(commit = False)
            u.role = 2
            u.save()
            messages.success(request,"Account Created Successfully")
            new_user = authenticate(username=f.cleaned_data['username'],
                                    password=f.cleaned_data['password1'],
                                   )
            login(request, new_user)
            return redirect('home')
        else:
            messages.error(request,f.errors)
    return render(request,'init/userReg.html',{'form':f})


@login_required
def changepwd(request):
    if request.method =="POST":
        k = PasswordChange(user=request.user,data = request.POST)
        if k.is_valid():
            k.save()
            messages.success(request,"Password Changed Successfully")
            return redirect('/login')
        else:
            messages.error(request,"Can't Change your Password")
    cp = PasswordChange(user = request)
    return render(request,'init/changepwd.html',{'cp':cp})
@login_required
def camview(request,id):
    cam = CamModels.objects.get(id = id)
    return render(request,'init/camview.html',{'data':cam})

def deleteCam(request,id):
    v=CamModels.objects.get(id=id)
    if request.method == 'POST':
        messages.info(request,"Camera Deleted Successfully")
        v.delete()
        return redirect('home')
    
    return render(request,'init/deleteCam.html',{'data':v})

@login_required
def orderform(request,id):
    t = OrderModel.objects.filter(uid_id = request.user.id)
    emp=False
    f = OrderForm()
    if t.count() == 0:
        emp = True
        if request.method == "POST":
            f = OrderForm(request.POST)
            frm = request.POST.get('fromDate')
            to = request.POST.get('toDate')
            c_id = id        
            if f.is_valid():
                u = f.save(commit=False)
                u.cid = c_id
                u.uid_id = request.user.id
                u.uUname = User.objects.get(id = request.user.id).username
                if parseTheEvent(frm,to,c_id):
                    u.save()
                    
                    messages.info(request,"Order recorded Successfully")
                    return redirect('home')
                else:
                    pass
                    messages.warning(request,"Camera is already booked by another person on this period")
    return render(request,'init/orderform.html',{'form':f,'data':emp})
    

def parseTheEvent(a,b,c):
    x = CamModels.objects.get(id = c)
    z = x.bookedDates
    if z == '':
        res = z+a+"_"+b+"/"
    else:
        z.split('/')
        p = a+"_"+b+"/"
        if p in z:
            return False
        else:
            res = z+p
    x.bookedDates = res
    x.save()
    return True

@login_required
def myorders(request):
    lst = []
    emp = True
    ord = OrderModel.objects.all()
    for i in ord:
        cId = i.cid
        cm = CamModels.objects.get(id = cId)
        vid = cm.vgId_id
        if vid == request.user.id:
            lst.append(i)
            emp = False
    if lst == []:
        emp = True
    return render(request,'init/myorders.html',{'data':lst,'emp':emp})

@login_required
def viewCustOrder(request,id):
    t = OrderModel.objects.get(id=id)
    em = t.email
    print(em)
    if request.method == 'POST':
        f = viewCustOrderForm(request.POST,instance=t)
        if f.is_valid():
            u = f.save()
            r = emailSend(request,u.isAccepted,em)
            return redirect('myorders')
    f = viewCustOrderForm(instance=t)
    return render(request,'init/viewCustOrder.html',{'form':f})

def emailSend(request,n,em):
    ls = []
    print(em)
    ls.append(em)
    print('ls',ls)
    if n == 2:
        sd = ls
        print(sd)
        mg = 'Your Order had been Accepted'
        sm = 'Order-ACCEPTED'
        rt = settings.EMAIL_HOST_USER   
        dt = send_mail(sm,mg,rt,sd)
    elif n==3:
        sd = ls
        mg = 'Your Order had been Rejected'
        sm = 'Order-REJECTED'
        rt = settings.EMAIL_HOST_USER   
        dt = send_mail(sm,mg,rt,sd)
    return dt

def mybookings(request):
    t = OrderModel.objects.filter(uid_id = request.user.id)
    emp=False
    if t.count == 0:
        emp = True
    return render(request,'init/mybookings.html',{'emp':emp,'data':t})

MyVideoGrapher/init/templates/init/addCam.html
{% extends 'init/base.html' %}
{% block title %} Add Your Camara {% endblock %}
{% block content %}

    <div class="container mt-4">
        <div class="card">
                <div class="card-body">
                    <h3>Add on Your Camera</h3>
                    <form enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {% for i in form %}
                            {{i}}
                        {% endfor %}
                        <div class="row">
                            <div class="col">
                                <a href="{% url 'home' %}" class = "btn btn-outline-danger my-2 form-control">Back To Home page</a>
                            </div>
                            <div class="col">
                                <input type = "reset" name = "Reset" class = "btn btn-outline-info my-2 form-control">
                            </div>
                            <div class="col">
                                <input type = 'submit' text-lightpe="submit" name = "Create" placeholder="Proceed to Home Page" class = "btn btn-outline-success my-2 form-control">
                            </div>
                        </div>  
                    </form>
                </div>
        </div>
    </div>

{% endblock %}

MyVideoGrapher/init/templates/init/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    
</head>
<body>
  {% include 'init/navbar.html' %}
  <div class="container mt-4">
    
    {% if messages %}
    {% for m in messages %}
    <div class="alert alert-{{m.tags}} alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{m}}
      </div>
    {% endfor %}
    {% endif %}
  </div>
    {% block content %}
    {% endblock %}
</body>
<!-- Footer -->
<footer class="page-footer font-small blue pt-4 " style="background-color: #8acdfd;">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">
  
      <!-- Grid row -->
      <div class="row">
  
        <!-- Grid column -->
        <div class="col-md-5 mt-md-0 mt-3">
  
          <!-- Content -->
          <h3 class="text-uppercase">MyVideoGrapher.com</h3>
          <p>Here you can choose your prefect videographer for your Events</p>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none pb-3">
  
        <!-- Grid column -->
        <div class="col-md-4 mb-md-0 mb-3">
  
          <!-- Links -->
          <h5 class="text-uppercase">Links(studio)</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'home' %}">Home</a>
            </li>
            <li>
              <a href="{% url 'setupStudio' %}">Set Up Your Studio</a>
            </li>
            <li>
              <a href="{% url 'login' %}">Login to your Existing Studio</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
  
          <!-- Links -->
          <h5 class="text-uppercase">Links(User)</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'home' %}">Home</a>
            </li>
            <li>
              <a href="{% url 'setupStudio' %}">Register new Account</a>
            </li>
            <li>
              <a href="{% url 'login' %}">Login to your Account</a>
            </li>
          </ul>
  
        </div>
        
  
        </div>
    </div>
    
    <!-- Footer Links -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2021 Copyright:
      <a href="{% url 'home' %}"> MyVideoGrapher</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->
</html>

MyVideoGrapher/init/templates/init/camaraDetails.html
{% extends 'init/base.html' %}
{% block title %} The Camara Details {% endblock %}
{% block content %}

    <div class="container mt-4">
        <div class="card">
            <div class="card-body">
                <h3>Details of this camara</h3>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for i in form %}
                        {{i}}
                    {% endfor %}                
                <div class="row">
                    <div class="col">
                        <a href="{% url 'home' %}" class = "btn btn-outline-danger my-2 form-control">Back To Home page</a>
                    </div>
                    <div class="col">
                        <input type = "reset" name = "Reset" class = "btn btn-outline-info my-2 form-control">
                    </div>
                    <div class="col">
                        <input type = 'submit' text-lightpe="submit" name = "Create" placeholder="Proceed to Home Page" class = "btn btn-outline-success my-2 form-control">
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>

{% endblock %}

MyVideoGrapher/init/templates/init/camview.html
{% extends 'init/base.html' %}
{% block title %} Change Password {% endblock %}
{% block content %}

<div class="container mt-4">

<div class="card">
    <div class="card-head text-center">
        <h3>The Full Details of Your Camera:</h3>
    </div>
        <div class="card-body row">
            <div class="col">
                <img src="{{ data.camPic.url }}" class="d-block w-75">
            </div>
            <div class="col">
                <table class="table">
                    <tbody>
                        <tr>
                          <td>Camera Name:</td>
                          <td><h1>{{ data.camName }}</h1></td>
                          
                        </tr>        
                        <tr>
                          <td>The cost per day</td>
                          <td>{{ data.prizePerHour }}</td>
                          
                        </tr>
                        <tr>
                          <td>Brief Description: </td>
                          <td>{{ data.description }}</td>
                          
                        </tr>
                        <tr>
                            {% if user.role == 1 %}
                            <td><a href="{% url 'editCamdetails' data.id %}" class="btn btn-outline-info my-2 form-control"> Edit </a></td>
                            <td><a href="{% url 'deleteCam' data.id %}" class="btn btn-outline-danger my-2 form-control">Delete</a></td>
                            {% else %}
                            <td><a href="{% url 'orderform' data.id %}" class="btn btn-outline-info my-2 form-control"> Book My Order </a></td>
                            {% endif %}
                        </tr>
                      </tbody>
                </table>
            </div>
        </div>
</div>
</div>
{% endblock %}

MyVideoGrapher/init/templates/init/deleteCam.html
{% extends 'init/base.html' %}
{% block title %}Delete Resturent{% endblock %}
{% block content %}
<div class="container mt-4">
    <div class="card col-md-6 mx-auto shadow-lg">
        <div class = "card-body">
            <h3>Deleting A Camara</h3>
            <form method="POST">
                {% csrf_token %}
                <h4>Are you sure you want to delete {{data.camName}}</h4>
                <div class="row">
                    <div class="col">
                        <input type="submit" value = "yes Conform" class= 'btn btn-outline-success my-2 form-control' >
                    </div>
                    <div class= "col">
                        <a href="{% url 'camView' data.id %}" class="btn btn-outline-danger my-2 form-control"> Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

MyVideoGrapher/init/templates/init/eventDetails.html
{% extends 'init/base.html' %}
{% block title %} The Camara Details {% endblock %}
{% block content %}

<div class="container mt-4 row">
    <div class="col">
        <div class="card mt-4"> 
            <div class="card-head text-center">
                <h3>View the camaera's we had </h3>
            </div>
            <div class="card-body" style="display:flex;flex-wrap: wrap;">
              {% for i in cam %}
              <div class="col" ></div>
              <div class="card col-md-4 my-2 mx-2">
               <img class="d-block w-100" height="200px" width="200px" src="{{ i.camPic.url }}">
               <div class="card-body">
                 <h5 class="card-title">{{ i.camName }}</h5>
                 <p class="card-text">{{ i.description }}</p>
                 <div class="row">
                   <a href="#" class="col mx-2 form-control btn btn-primary">Check Availability</a>
                   
                 </div>
                 
               </div>
             </div>    
             {% endfor %}
            </div>
        </div>
    </div>
    <div class="card col">
        <div class="card-body">
            <div class="col">
                <h3>Fillout the details, to show the available camera's...</h3><hr>
                <form method="post">
                    
                    <label for="id_nameOfEvent">NameOfEvent:</label>
                    <input type="text" name="nameOfEvent" class="form-control my-2" placeholder="Enter your Name" maxlength="100" required id="id_nameOfEvent">

                    <label for="id_fromDate">FromDate:</label>
                    <input type="date" name="fromDate" class="form-control my-2" placeholder="Enter Starting day of event:" maxlength="50" required id="id_fromDate">

                    <label for="id_toDate">ToDate:</label>
                    <input type="date" name="toDate" class="form-control my-2" placeholder="Enter Ending day of event:" maxlength="50" required id="id_toDate">

                    <label for="id_ceremonyTime">CeremonyTime:</label>
                    <input type="time" name="ceremonyTime" class="form-control my-2" placeholder="Enter Timings" maxlength="50" required id="id_ceremonyTime">
                    
                    <label for="id_addressOfCeremony">AddressOfCeremony:</label>
                    <textarea name="addressOfCeremony" cols="40" rows="3" class="form-control my-2" placeholder="Mention Event location" required id="id_addressOfCeremony"></textarea>
            </div>

            <div class="row">
                <div class="col">
                    <input type = "reset" name = "Reset" class = "btn btn-outline-danger my-2 form-control">
                </div>
                <div class="col">
                    <input type = 'submit' text-lightpe="submit" name = "Create" class = "btn btn-outline-success my-2 form-control">
                </div>
            </div>
            
        </div>
    </div>
</div>
{% endblock %}

MyVideoGrapher/init/templates/init/gendralHome.html
{% load static %}
<div class="container mt-5">
  <div class="row">
      <div class="col card rounded border-primary" >
          <div class="card-body text-center">
              <div class="text-justify text-center ">
                  <br><br><br>
                  <h2>Welcome to, <br> MyVideoGrapher.com</h2><br>
                  <h5>Moments Simply Captured</h5>
              </div>
          </div>
      </div>
      <div class="col">
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
              </ol>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block w-100" src="{% static 'images/01.jpg' %}" alt="First slide">
                  <div class="carousel-caption d-none d-md-block">
                      <h5 class="text-bold">Add your Studio</h5>
                      <p><a href="{% url 'setupStudio' %}" class="btn btn-secondary btn-lg">Here!</a></p>
                    </div>
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="{% static 'images/02.jpg' %}" alt="Second slide">
                  <div class="carousel-caption d-none d-md-block">
                    <h5 class="text-bold">Add your Studio</h5>
                    <p><a href="{% url 'setupStudio' %}" class="btn btn-secondary btn-lg">Here!</a></p>
                    </div>
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="{% static 'images/03.jpg' %}" alt="Third slide">
                  <div class="carousel-caption d-none d-md-block">
                    <h5 class="text-bold">Add your Studio</h5>
                    <p><a href="{% url 'setupStudio' %}" class="btn btn-secondary btn-lg">Here!</a></p>
                    </div>
                </div>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
      </div>
  </div>
  <br>
  <hr>
  {% include 'init/videographerCatalog.html' %}
</div>

MyVideoGrapher/init/templates/init/mybookings.html
{% extends 'init/base.html' %}
{% block title %} Your Bookings {% endblock %}
{% block content %}

<div class="container-fluid mt-4">
  {% if not emp %}
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="row">srno.</th>
            <th scope="row">Name of Event</th>
            <th scope="row">Email Address</th>
            <th scope="row">Order From</th>
            <th scope="row">from Date</th>
            <th scope="row">to Date</th>
            <th scope="row">Ceremony Time</th>
            <th scope="row">Address of Event</th>
            <th scope="row"> Status </th>
            
          </tr>
        </thead>
        <tbody>
          {% for i in data %}  
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ i.nameOfEvent }}</td>
            <td>{{ i.email }}</td>
            <td>{{ i.uUname }}</td>
            <td>{{ i.fromDate }}</td>
            <td>{{ i.toDate }}</td>
            <td>{{ i.ceremonyTime }}</td>
            <td>{{ i.addressOfCeremony }}</td>
            <td>
                {% if i.isAccepted == 1 %}
                <span class="badge badge-info">Not Responded</span>
                {% elif i.isAccepted == 2 %}
                <span class="badge badge-success">Accepted</span>
                {% else %}
                <span class="badge badge-danger">Rejected</span>
                {% endif %}
            </td>
            
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
        <div class="card col-md-6 mx-auto shadow-lg"> 
          <div class="card-body">
            <h3>
              You Dont Booked any contract with studios
            </h3>
            <a href="{% url 'home' %}" class = "btn btn-outline-info my-2 form-control">Search Here</a>
          </div>
        </div>
    {% endif %}
</div>

{% endblock %}

MyVideoGrapher/init/templates/init/orderform.html
{% extends 'init/base.html' %}
{% block title %} Register Studio {% endblock %}
{% block content %}

    
    <div class="container mt-4">
        {% if data %}
        <div class="card row">
            <div class="card-body">
                <div class="col">
                    <h3 class="card-head">Complete Your Order</h3><hr>
                    <form method="post">
                        {% csrf_token %}
                        
                    {{ form }}
                </div>
            <div class="row">
                <div class="col">
                    <input type = "reset" name = "Reset" class = "btn btn-outline-danger my-2 form-control">
                </div>
                <div class="col">
                    <input type = 'submit' text-lightpe="submit" name = "Create" class = "btn btn-outline-success my-2 form-control">
                </div>
            </div>
            <br>
        </form>
            </div>
        </div>
        {% else %}
            <div class = "card">
                <div class="card-body text-center">
                    <h3>You already had a Booking. So you cant book another once, until and unless The existing contract is Finished</h3>
                    <a href="{% url 'mybookings' %}" class = "btn btn-outline-info my-2 form-control">Check Your Contract Here!</a>
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}

MyVideoGrapher/init/templates/init/studioProfileInfo.html
{% extends 'init/base.html' %}
{% block title %} Login To Your Studio {% endblock %}
{% block content %}

    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h3 class="text-justify text-center">
                    SetUp your Profile
                </h3>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for i in form %}
                        {{i}}
                    {% endfor %}

                    <div class="row">
                        <div class="col">
                            <a href="{% url 'home' %}" class = "btn btn-outline-danger my-2 form-control">Back To Home page</a>
                        </div>
                        <div class="col">
                            <input type = "reset" name = "Reset" class = "btn btn-outline-info my-2 form-control">
                        </div>
                        <div class="col">
                            <input type = 'submit' text-lightpe="submit" name = "Create" placeholder="Proceed to Home Page" class = "btn btn-outline-success my-2 form-control">
                        </div>
                        
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}